### ISSUE TITLE
ScureCRT 9.4

### ISSUE THREAD

**Issue by llxiaoyuan** [HyperSine/how-does-SecureCRT-encrypt-password#4]
ScureCRT 9.4 with a new type encryption，"Password V2"=03:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

**Comment by HyperSine** [comment]
updated for SecureCRT 9.4+, you can have a look to the new readme.

**Comment by llxiaoyuan** [comment]
greatttt workkkk sir！！！
